### ISSUE TITLE
Service Implementation

### ISSUE THREAD

**Issue by AthulKrishna14310** [saneenKP/food-app#13]
- [x] **Service Switch should turn on NotifyService**
- _Switch can be only turned on if phone number and name field is not empty else show error message_
- _Switch action should be saved in shared preference so that switch won't get disabled when app closes_

- [x] **Delivery boy can assign the order to himself**
- _Cardview should display as the order is assigned by 'Delivery boy name'_
- _Once order assigned , it cannot be unassigned . Design the checkbox ui accordingly_

- [x]  **Service should check for orders and new recent oders should be notified to delivery boy**
- _Assigned order must not be notified_
- _Notification should be a high priority one_
- _Notification text will be "New order placed"_

- [x] **Update Delivery boy details to client App**
- _Clone the enhancement branch from github_
- _When delivery boy assigns the order, diplay his name and phone number on the OrderProcess activity_

If you have any additional recommends , please mention

**Comment by SaneenKP** [comment]
Shared Preferences to save Delivery Boy Details ?

**Comment by SaneenKP** [comment]
assign button should only be clickable if the name and number fields are accurate

**Comment by AthulKrishna14310** [comment]
> Shared Preferences to save Delivery Boy Details ?
> 

Shared Preference just to control switch

**Comment by AthulKrishna14310** [comment]
> assign button should only be clickable if the name and number fields are accurate 
> 

Yes..
